version: "3"
services:
  whats-document-sign:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - session:/app/_IGNORE_session
      - ./session.data.json:/app/session.data.json
      - ./signature.pfx:/app/signature.pfx:r
    env_file:
      - .env
volumes:
  session: