version: "3"
services:
  whats-document-sign:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/app/.env
      - session:/app/_IGNORE_session
      - session-json:/app/session.data
      - ./signature.pfx:/app/signature.pfx
volumes:
  session:
  session-json: